repos:
  - repo: local
    hooks:
      - id: catalog-guard
        name: Catalog guard (commit-msg)
        entry: python scripts/semantic_versioning.py
        language: system
        stages: [commit-msg]